- ignore: {name: Eta reduce}
- ignore: {name: 'Use -'}
- ignore: {name: Use if}
- ignore: {name: Use head}
- ignore: {name: Use <$>}
- ignore: {name: Use first}
- ignore: {name: 'Use ?~'}
- ignore: {name: 'Move brackets to avoid $'}
- ignore: {name: Avoid lambda}
- ignore: {name: Avoid lambda using `infix`}

- ignore: {name: Use isAsciiLower}
- ignore: {name: Use isAsciiUpper}
- ignore: {name: Use isDigit}
- ignore: {name: Use unwords}
- ignore: {name: Use foldMap}
# Replace a $ b $ c with a . b $ c
#- group: {name: dollar, enabled: true}

# Generalise map to fmap, ++ to <>
- group: {name: generalise, enabled: true}

# To generate a suitable file for HLint do:
# $ hlint --default > .hlint.yaml
